import simbie from '../assets/simbie_transparent_background.png'
import '../styles/for_image.css'


//_____________________ Images for "WHAT IS" blocks _____________________

// Blocks 1X
import decentralized_image from '../assets/what_is/decentralization.png'
import tenacious_image from '../assets/what_is/tenacious.png'
import speed_image from '../assets/what_is/speed.png'

// Blocks 2X
import multi_level_sharding_image from '../assets/what_is/multi_level_sharding.png'
import post_quantum_image from '../assets/what_is/post_quantum.png'
import cloud_image from '../assets/what_is/cloud.png'


// Blocks 3X
import network_of_blockchains_image from '../assets/what_is/network_of_blockchains.png'
import multistaking_image from '../assets/what_is/multistaking.png'
import mutable_image from '../assets/what_is/mutation.png'



const WhatIs = () => {

    return (
        
        <div>

            <div className="container">

              <div className="box">
                <div className="imgBx">
                <img id="simbie" src={simbie}/>
                </div>
                <div className="content">
                  <div id="alt_for_mascot">
                    <h2>Simbie</h2>
                    <p>Simbie is a KLY mascot generated by Midjourney</p>
                  </div>
                </div>
              </div>
            </div>

            
            <div id="what_is_block">

            <section id="what_is_section" class="cyberpunk"> 

                <h2 id="what_is_answer" className>what is Klyntar</h2>

                <div className="what_is_inner">


                    <div className="what_is_elem">
                    
                        <img src={decentralized_image} width="40%"/>

                        <p>The most decentralized crypto project</p>

                        <hr/>

                        <div className="what_is_elem_content">

                            <p>KLY relies on all the blockchains in the industry like Bitcoin, Ethereum, Near, Cardano and others in matters of valid state resolution, rollbacks prevention, etc. Nothing can be more reliable than all the blockchains together😃</p>

                        </div>
                        
                    
                    </div>
    
                    <div className="what_is_elem">

                        <img src={speed_image} width="40%"/>
                        
                        <p>The fastest crypto project ever created</p>
                        
                        <hr/>

                        <div className="what_is_elem_content">

                            <p>Multilevel sharding + total parallelization + using TPS & TTF of other blockchains = 🤯🤯🤯</p>

                        </div>

                    </div>
    
                    <div className="what_is_elem">

                        <img src={tenacious_image} width="40%"/>

                        <p>The most fault tolerant crypto project</p>

                        <hr/>

                        <div className="what_is_elem_content">

                            <p>We will survive even if most of the crypto projects in the industry will be stopped / attacked / scammed. Thanks to the mechanism of migrations💀</p>

                        </div>
                        
                    </div>

                </div>

                <div className="what_is_inner">
    
                    <div className="what_is_elem">
                        
                        <img src={cloud_image} width="40%"/>
                        
                        <p>cloud-of-everything</p>

                        <hr/>

                        <div className="what_is_elem_content">

                            <p>EVM & WASM compatibility with unique functionality, Docker & K8S support coming soon, codeless RWX smart contracts and much more to build a FAANG-similar ecosystem of services🚀</p>

                        </div>

                    </div>
                    
                    <div className="what_is_elem">
                        
                        <img src={post_quantum_image} width="40%"/>
                        
                        <p>post quantum security</p>

                        <hr/>

                        <div className="what_is_elem_content">

                            <p>KLY is already quantum-secured with a set of PQC algorithms - for signatures, encryption and key exchange⚛️</p>

                        </div>
                        
                    </div>

                    <div className="what_is_elem">
                        
                        <img src={multi_level_sharding_image} width="40%"/>
                        
                        <p>multi-level sharding</p>

                        <hr/>

                        <div className="what_is_elem_content">

                            <p>The ecosystem is a set of independent blockchains - symbiotes(first level of sharding) which can be also sharded on a single-symbiote level(second level)🖖</p>

                        </div>
                        
                    </div>

                </div>

                  <div className="what_is_inner">
    
                    <div className="what_is_elem">

                        <img src={multistaking_image} width="40%"/>
                        
                        <p>multistaking</p>

                        <hr/>

                        <div className="what_is_elem_content">

                            <p>To be the most secure project with a maximal Nakamoto coefficient we need to have the biggest amount of locked stakes by independent entities. It's possible in the case of accepting NFTs, bitcoins, ethers and other stuff as a stake. Road to the multi-trillion protection🛡️</p>

                        </div>
                        
                    </div>

                    <div className="what_is_elem">

                        <img src={mutable_image} width="40%"/>
                        
                        <p>mutable project</p>

                        <hr/>

                        <div className="what_is_elem_content">

                            <p>Implement your improvement proposal, deploy it as a container and make the ecosystem better instantly⚡</p>

                        </div>

                    </div>

                    <div className="what_is_elem">
                    
                        <img src={network_of_blockchains_image} width="40%"/>
                    
                        <p>network of blockchains</p>

                        <hr/>

                        <div className="what_is_elem_content">

                            <p>Run your own symbiote in a KLY ecosystem to use the powers of the whole crypto industry - maximum security, decentralization, fault tolerance and speed🤝</p>

                        </div>
                        
                    </div>
                    

                </div>
                </section>
            </div>

        </div>

    )

}


export default WhatIs;